#!/usr/bin/env ruby
oldrev, newrev = ARGV

def run(cmd)
  exit($?.exitstatus) unless system "umask 002 && #{cmd}"
end

run "shards install --production --ignore-crystal-version"

run "shards build gbaldraw.cr --release --ignore-crystal-version"

run "npm install . && npm run release"