#!/usr/bin/env ruby

# deploy script

oldrev, newrev = ARGV

def run(cmd)
  exit($?.exitstatus) unless system "umask 002 && #{cmd}"
end

run "shards install --production --ignore-crystal-version"

run "shards build gbaldraw.cr --release --ignore-crystal-version"

run "/home/gbaldraw/node-v14.15.0-linux-x64/bin/npm install . && /home/gbaldraw/node-v14.15.0-linux-x64/bin/npm run release"