secret_key_base: xHCjTuWxcmCtshJGzM7KRCRfWuKV-jZPk8H3XpU-Wrk
port: 3000
name: openloft.cr

logging:
  severity: debug
  colorize: true
  filter:
    - password
    - confirm_password

host: 0.0.0.0
port_reuse: true
process_count: 1
# ssl_key_file:
# ssl_cert_file:
redis_url: "redis://127.0.0.1:6379"
database_url: sqlite3:./db/openloft.cr_development.db
auto_reload: true

session:
  key: amber.session
  store: signed_cookie
  expires: 0

smtp:
  enabled: false

pipes:
  static:
    headers:
      "Cache-Control": "no-store"

secrets:
  description: Store your development secrets credentials and settings here.
  PAYPAL_CLIENT_ID: AV41emd4rs8wUU-MHN_GS19wZcvMgwJavupuLV0ECsRd3776WCkhwbmrLPHjMAJIjDLB9JhueJzdWNg_
  PAYPAL_CLIENT_SECRET: EDqiPDDHq2VUDBlMtn3LJ4akj-aMga-se2xoOfU_ocpubqBeCzM-UTzB3bgnx8cuwPEohBId_3NWEzKK
  SLACK_SIGNING_SECRET: none
  SLACK_ID_TOKEN: none
  REDIS_PASSWORD: 1234 
  discord_token: ODQ2NjQ0MDk4NTQ2NjYzNDQ0.YKygwg.teJ_tvts0WouRNvwinjtVKE8bIE
  discord_client_id: 846644098546663444
  ircbot_enabled: true
  discord_enabled: true
  server: irc.libera.chat
  user: openloft
  nick: openloft-bridge
  password:
  channel: "#openloft"